server:
  port: 20001
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest1?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  session:
    store-type: none

jwt.secret:
  key: 37c975e917b24d41834643c47a83ad20
  access-token-expires-in: 15
  refresh-token-expires-in: 21600
  refresh-token-expires-threshold: 30