server:
  port: 20001
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest1?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

jwt.secret:
  key: 37c975e917b24d41834643c47a83ad20
  jwt-header: COP_Authorization
  # token 过期时间 分钟
  token-expires-in: 120
  # refresh 过期时间 15天
  refresh-token-expires-in: 21600
  # refresh 过期阈值 30分钟
  refresh-token-expires-threshold: 30

encryption:
  # 密码加密的盐值
  salt-value: 3bcbb857c763d1429a24959cb8de2593
  #MD5的散列次数
  hash: 1024
