server:
  port: 20001
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest1?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

jwt.secret:
  key: 37c975e917b24d41834643c47a83ad20
  token-expires-time: 15
  refresh-token-expires-in: 21600
  refresh-token-expires-threshold: 30
